# infra/k8s/helm/elasticsearch/elasticsearch-values.yaml
# Official Elastic chart — elasticsearch 8.5.1

replicas: 1

esJavaOpts: "-Xmx512m -Xms512m"

esConfig:
  elasticsearch.yml: |
    # Empty config since discovery.type is removed
# Soft anti-affinity required for single-node clusters
antiAffinity: "soft"

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 8Gi

resources:
  requests:
    cpu: "50m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

readinessProbe:
  failureThreshold: 10
  initialDelaySeconds: 30

# Runs `sysctl -w vm.max_map_count=262144` on pod startup
sysctlInitContainer:
  enabled: true
