global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: mohamedosa/halan-frontend
  tag: "latest"

replicaCount: 1 
service:
  type: ClusterIP  
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPU: 50


serverBlock: |-
  server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy /api calls to the backend Flask container
    location /api/ {
        proxy_pass http://halan-backend-service:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
