apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Source 1: Bitnami Elasticsearch chart (same repo as nginx, postgres, etc.)
    - repoURL: https://charts.bitnami.com/bitnami
      chart: elasticsearch
      targetRevision: "22.1.6"
      helm:
        # $values refers to Source 2 below — ArgoCD resolves it at sync time
        valueFiles:
          - $values/infra/k8s/helm/elasticsearch/elasticsearch-values.yaml

    # Source 2: Your Git repo — used ONLY to load the values file above
    - repoURL: https://github.com/mohamed0s/Halan-Internship-Project
      targetRevision: HEAD
      ref: values # This names the source "$values" for the reference above
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
