apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: halan-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/mohamed0s/Halan-Internship-Project
    targetRevision: HEAD
    path: infra/k8s/helm/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: halan
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
