apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: halan-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohamed0s/Halan-Internship-Project
    targetRevision: HEAD
    path: infra/k8s
    directory:
      recurse: false
      exclude: "job.yaml"  # Exclude one-shot DB migration — managed via bootstrap only
  destination:
    server: https://kubernetes.default.svc
    namespace: halan
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
