apiVersion: v1
kind: ConfigMap
metadata:
  name: db-seed-sql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  01-init.sql: |-
    {{ .Files.Get "sql/01-init.sql" | nindent 4 }}
