apiVersion: v1
kind: Service
metadata:
  labels:
    app: halan-backend-service
  name: halan-backend-service
  namespace: halan

spec:
  selector:
    app: halan-backend 
  
  ports:
    - port: 5000
      targetPort: 5000

  type: ClusterIP
