# infra/k8s/config/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: halan-db-secret
  namespace: halan
type: Opaque
stringData:
  postgres-password: super_secret_production_password # The admin password
  password: super_secret_production_password # The app user password
