# infra/k8s/helm/postgres/postgres-values.yaml
architecture: replication # Enables Primary + Read-Replica setup

auth:
  database: db
  username: pguser
  existingSecret: halan-db-secret

primary:
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard" # Explicitly set to avoid relying on hidden defaults!
    # TODO (Phase 15.1): Change 'standard' to 'longhorn' when migrating to RKE

readReplicas:
  replicaCount: 2 # Number of read-only replica pods
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard"