# infra/k8s/helm/postgres/postgres-values.yaml
architecture: replication # Enables Primary + Read-Replica setup
fullnameOverride: "halan-db-postgresql"

auth:
  database: halandb
  username: pguser
  existingSecret: halan-db-secret

primary:
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "longhorn"
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

readReplicas:
  replicaCount: 1 # Number of read-only replica pods
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "longhorn"

primary:
  podLabels:
    app: halan-postgres
    version: "18.8.12"

readReplicas:
  podLabels:
    app: halan-postgres
    version: "18.8.12"
